# Generated by Django 4.2.11 on 2024-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_fundrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundrequest',
            options={},
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='approved_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
