# Generated by Django 4.2.11 on 2024-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_fundrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
