# Generated by Django 4.2.11 on 2024-04-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_wallet_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='approved_at',
        ),
    ]
