# Generated by Django 4.2.11 on 2024-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_fundrequest_options_fundrequest_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
